### ISSUE TITLE
Are CSS Modules supported with Brunch 2.7?

### ISSUE THREAD

**Issue by pcattori** [brunch/css-brunch#9]
The docs say `<unreleased>` but haven't been updated for a while. Is this implemented for Brunch 2.7.x?

Found this as well, which seems to indicate that CSS Modules are supported since Brunch 2.6: https://www.npmjs.com/package/sass-brunch#css-modules , but says to use the `plugins.sass` key when using the `sass-brunch` plugin. I would assume that the `plugins.css` key will work for `css-brunch`?

**Comment by paulmillr** [comment]
they are. yes, you're correct.

**Comment by paulmillr** [comment]
`{plugins: {css: {modules: true}}}` and etc for `sass`
